### ISSUE TITLE
Jenkins kinks and issues

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia-blueprint#109]
### Bug Description:

Our Jenkins build is not very stable at the moment. I noticed a few things in the Jenkins build log, that I'll attempt to fix.

- [linux] Suitable yarn cache global folder not found
  - _potential fix:_  I think we can add the `/.yarn` folder, so that it's writable by our CI user, using a volume, like we do for the `/.cache` folder.

```bash
theia-blueprint-updater: warning Cannot find a suitable global folder. Tried these: "/usr/local, /.yarn"
```

- [linux] it looks like during packaging, there's a failed attempt to create a `/.npm` folder (permission denied). Same solutiuon as above: add a volume for this folder
`WARN install EACCES: permission denied, mkdir '/.npm'` (*) full trace

- [linux] For whatever reason, I notice that the Linux installer build seems to fail often on the first try. We should have a re-try mechanism, if it can help successful runs - to be confirmed. 

### Steps to Reproduce:

Look at the  in the Jenkins build log, e.g. for a build of the master branch. 

### Additional Information

(*) full trace
```
$ rimraf dist
  • electron-builder  version=22.10.5 os=5.10.19-200.fc33.x86_64
  • loaded configuration  file=/home/jenkins/agent/workspace/theia-example_PR-107/applications/electron/electron-builder.yml
  • rebuilding native dependencies  dependencies=@theia/node-pty@0.9.0-theia.6, drivelist@9.2.4, find-git-repositories@0.1.3, native-keymap@2.2.1, nsfw@2.1.2, oniguruma@7.2.1 platform=linux arch=x64
  • install prebuilt binary  name=drivelist version=9.2.4 platform=linux arch=x64
  • build native dependency from sources  name=drivelist
                                          version=9.2.4
                                          platform=linux
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.6
    prebuild-install info npm cache directory missing, creating it... 
    prebuild-install WARN install EACCES: permission denied, mkdir '/.npm'
```

---
- Operating System: Linux
- Theia Version:

**Comment by marcdumais-work** [comment]
@thegecko Do you know how one gets access to see/edit the Jenkins job configuration? I do not seem to have that access.

**Comment by thegecko** [comment]
I think I can see some of it,  but the interesting stuff is all in the jenkinsfile as far as I can remember.  What are you after?

**Comment by marcdumais-work** [comment]
In the logs I sometimes see a "git clean -ffdx" that seems to hang, that's not from the Jenkinsfile, I think. That's in the mac section, "sign, notarize and upload".I thought it might be in the job's config.

**Comment by thegecko** [comment]
Just checked and the config only contains checkout details and repo discovery settings, there's no additional scripting.

**Comment by marcdumais-work** [comment]
Ok, thanks Rob. While in there, might there be references to the repo under it's old/original name? I see some of these in the logs.

**Comment by thegecko** [comment]
It was using the old repo URL, so have updated it. It's likely this change will have scheduled new builds for all PRs...
