### ISSUE TITLE
Blueprint does not consider extension installation recommendations

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-blueprint#122]
### Bug Description:
If a repository recommends extensions to be installed via extensions.json, Theia blueprint does not suggest to install them.

### Steps to Reproduce:

Checkout a repository with recommended extensions, e.g. https://github.com/eclipse-theia/theia
No recommendations are shown.
Should suggest eslint, see https://github.com/eclipse-theia/theia/blob/master/.vscode/extensions.json

**Comment by vince-fugnitto** [comment]
@JonasHelming it should be available when bumping the theia version https://github.com/eclipse-theia/theia/pull/9043.

**Comment by JonasHelming** [comment]
Great! Let us leave this open until then, I assigned a label to keep track

**Comment by vince-fugnitto** [comment]
Closed thanks to #141.

**Comment by JonasHelming** [comment]
@vince-fugnitto : Have you verified this in the Blueprint build or only upstream?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto : Have you verified this in the Blueprint build or only upstream?

During the review, please feel feee to confirm as well: https://github.com/eclipse-theia/theia-blueprint/pull/141#pullrequestreview-728546106.

**Comment by marcdumais-work** [comment]
> During the review, please feel free to confirm as well: [#141 (review)](https://github.com/eclipse-theia/theia-blueprint/pull/141#pullrequestreview-728546106).

I have not re-tested this, but I have confirmed that the new Blueprint installers, based on Theia v1.16.0, were correctly deployed. (linux: https://www.eclipse.org/downloads/download.php?file=/theia/latest/linux/TheiaBlueprint.AppImage&r=1)
