### ISSUE TITLE
Eclipse key bindings are built in

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-blueprint#123]
### Bug Description:
Blueprint comes with the Eclipse bindings built in. Therefore they cannot be uninstalled and may overlap with user defined bindings
We should either remove them or make them uninstallable.

### Steps to Reproduce:

Install VS Code bindings and press CTRL+D, it will delete the line instead of marking the text and finding the next occurence.

**Comment by JonasHelming** [comment]
@lucas-koehler

**Comment by vince-fugnitto** [comment]
@JonasHelming I believe it relates to https://github.com/eclipse-theia/theia-blueprint/issues/81?
We probably do not want to enforce extensions to end-users, but rather let them install them? 

Ideally we would implement the mechanism in the framework to be able to disable extensions except `vscode-builtins-*` (https://github.com/eclipse-theia/theia/issues/7558).

**Comment by JonasHelming** [comment]
Is there currently a way to pre-install an extension, but still letting the user deinstall it?

**Comment by JonasHelming** [comment]
Also we might consider to install the VS Code keybindings by default

**Comment by vince-fugnitto** [comment]
> Is there currently a way to pre-install an extension, but still letting the user deinstall it?

For builtins (bundled) extensions, there is no way to `uninstall` them as they are treated as part of the application.
The idea however would be to allow end-users the ability to `disable` them similarly to vscode.

> Also we might consider to install the VS Code keybindings by default

There is no vscode keybinding extension, the framework uses the vscode keybindings by default.

**Comment by JonasHelming** [comment]
Digging a little deeper, the issue seems rather that blueprint comes with a mixture between VS Code and Eclipse.
CTRL+D is bound twice, the Eclipse (delete line) wins
SHIFT+F12 and F3 show caller
F12 does nothing in blueprint, should got to definition
CTRL+. does nothing in blueprint, should open quick fix

**Comment by JonasHelming** [comment]
@vince-fugnitto : Do you know where the default key bindings are defined? I want to have a look...

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto : Do you know where the default key bindings are defined? I want to have a look...

You'll need to look at the source code, or you can use the `keyboard shortcuts` view to view them (File > Settings > Open Keyboard Shortcuts).

**Comment by koegel** [comment]
I suggest to try to remove the Eclipse keybindings to get back to the default.

**Comment by JonasHelming** [comment]
Yes, working on that!

**Comment by vince-fugnitto** [comment]
@JonasHelming I believe you missed the test-case (which will fail the suite):

https://github.com/eclipse-theia/theia-blueprint/blob/d9def0d562707c79c5d88a17b14e4ee1a266c81a/applications/electron/test/app.spec.js#L129
