### ISSUE TITLE
Update old dependency: Browserslist: caniuse-lite

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia-blueprint#127]
### Bug Description:

During the build, we get the following warning: 

_Browserslist: caniuse-lite is outdated . Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating_

It looks like this is an easy, desirable thing to do.

### Steps to Reproduce:

1. build blueprint
2. notice the warning above. e.g.:

![image](https://user-images.githubusercontent.com/25749063/126702981-0ffde229-f475-4b46-96b4-088ede641b9a.png)

### Additional Information

- Operating System:
- Theia Version:

**Comment by marcdumais-work** [comment]
Note: I expect that the result of the provided update command should only be to update our `yarn.lock`, to pin a later version of `caniuse-lite`

**Comment by marcdumais-work** [comment]
Hi @Atharva321, 

Would you like to do a PR for this one? It should result in a mild `yarn.lock` change only.

**Comment by Atharva321** [comment]
Yes. But not able to understand the how issue will be fixed 

need some time.
 what i understood is after the build command it is generating the warning .
And where to make change in yarn.lock?

Can you elaborate more?

**Comment by marcdumais-work** [comment]
Hi @Atharva321 ,

I think you would need to build the repo (```yarn```) and then run the command from the description (```npx  [...]```). Then make sure the changes look ok (specially anything changed beyond `yarn.lock`), check-them-in and submit a PR

**Comment by marcdumais-work** [comment]
The warning in the issue's description was something I noticed during the build - essentially our `browserslist` dependency is telling us that its own `caniuse-lite` dependency is outdated and we need to update it, then provides the command to do so.

**Comment by Atharva321** [comment]
got it now.
