### ISSUE TITLE
generated  gitignore is too strict

### ISSUE THREAD

**Issue by duncdrum** [eclipse-theia/theia-blueprint#134]
### Bug Description:
When using this template the generated `.gitignore` contains 
```
webpack.config.js
```
since the file is for user modifications, in combination with  `gen-webpack.config.js` it makes no sense to have it ignored  (while still being checked into the git tree) OOTB. 

While it is easy for users to manualy unignore the file, it should be a simple fix to remove it from the `.gitignore` here and save everyone the hassle. 

### Steps to Reproduce:

1. Follow usage guide in readme
2. Check applied gitignore when moving generated files into a git repo

### Additional Information

- Operating System: all
- Theia Version: all

see https://github.com/theia-ide/yangster-electron/issues/33

**Comment by marcdumais-work** [comment]
Hi @duncdrum 

> it makes no sense to have it ignored (while still being checked into the git tree) OOTB.

Currently, it seems that `webpack.config.js` is both ignored and not part of the git source tree. If we proceed with this change, I guess it would make sense to also check it in, correct? And I think also to commit any future changes, like we usually do for `yarn.lock`?

The following SO question/accepted answer seems to confirm that this config file should generally be checked-in:

https://stackoverflow.com/questions/55166226/webpack-does-webpack-config-js-get-commited

cc: @paul-marechal WDYT?

**Comment by vince-fugnitto** [comment]
I believe `webpack.config.js` should not be gitignored and included in the repository, the generated `gen-webpack.config.js` should be ignored however. It also follows the examples we have in the main repository:
- https://github.com/eclipse-theia/theia/blob/master/examples/browser/webpack.config.js
- https://github.com/eclipse-theia/theia/blob/master/examples/electron/webpack.config.js

**Comment by marcdumais-work** [comment]
@duncdrum would you submit a PR to fix this?

**Comment by duncdrum** [comment]
Will do
