### ISSUE TITLE
Enable and document customization

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-blueprint#14]
Enable to customize this installer and document how to build installers for custom Theia-based products.

**Comment by koegel** [comment]
We (EclipseSource) intend to work on this on behalf of ST Microelectronics.

**Comment by koegel** [comment]
We are currently working on a GoogleDoc to create the documentation on how to customize the blueprint product to build installers for custom Theia-based products.

**Comment by koegel** [comment]
We would like to contribute the documentation to the Theia webpage and opened an issue in the corresponding repo to discuss how and where to contribute it:
https://github.com/theia-ide/theia-website/issues/131

**Comment by jfaltermeier** [comment]
Available here: https://theia-ide.org/docs/blueprint_documentation/
