### ISSUE TITLE
Proposal: streamline Blueprint CI - only use Jenkins when needed, rely on GH workflow more

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia-blueprint#148]
### Feature Description:

At the moment, our Jenkins CI step runs:
- when we merge a PR on the `master` branch
- when a PR is created and then every time the PR branch is updated. 

The former is necessary, so that Blueprint packages are created, signed/notarised (as appropriate for a given operating system) and uploaded to the EF download page. This essential activity is sometimes hindered by numerous concurrent PR-related Jenkins runs. 

For PRs, the value of running the Jenkins CI step is less clear.  All-in-all, it's typical to spend 1+h in Jenkins CI time, each time a PR branch is updated: 

![image](https://user-images.githubusercontent.com/25749063/129759684-1a8b71e4-7fa0-411e-8dba-5ae25516c69e.png)

We have recently added a [GitHub workflow](https://github.com/eclipse-theia/theia-blueprint/blob/master/.github/workflows/build.yml) that gives us rapid feedback about updated PRs on our 3 target platforms. ATM it just builds the repo (`yarn`) but can easily be enhanced to also build the various packages and run our modest test suite.

# Proposal: 
For PRs, why not generally skip Jenkins CI and instead use our GH workflow to build and test packages for our various operating systems. This will save a lot of CI time and insure Jenkins executor are available when we really need them: when we merge to master and want new packages generated, signed and uploaded.

In more details, I propose that we: 
    
- enhance the GH workflow to generate the packages for our various operating systems and run our modest test suite on them. This will give us an idea if we broke something, before merging a PR.
- only run Jenkins CI when merging on master or when we have reasonable suspicion(1) that the PR makes changes related to the Jenkins configuration. In that case we probably want Jenkins to run as it does today on PRs, so we can detect Jenkins-related issues, without having to merge to master first.

(1) e.g. when the word "jenkins" appears in the Pull Request title or PR branch name.

**Comment by marcdumais-work** [comment]
cc: @vince-fugnitto @thegecko @JonasHelming

**Comment by JonasHelming** [comment]
@koegel

**Comment by koegel** [comment]
Good idea imho! Should we try to implement this? @jfaltermeier

**Comment by marcdumais-work** [comment]
@koegel I have a PR ready: https://github.com/eclipse-theia/theia-blueprint/pull/143

**Comment by koegel** [comment]
@jfaltermeier is out of office today, he can likely take a look tomorrow though.
