### ISSUE TITLE
Releases of Blueprint in lockstep with Eclipse Theia

### ISSUE THREAD

**Issue by Jeeppler** [eclipse-theia/theia-blueprint#167]
My expectation as a user and developer is, that once a new Eclipse Theia release is published the Theia Blueprint project will release a new release of Blueprint based on the latest Eclipse Theia version soon afterwards.

I see two major reasons:

1. As a user I want to try the newest version of Eclipse Theia
2. As a developer I need to test my plugins

Currently, Eclipse Theia is in version 1.18 and Blueprint is based on version 1.17.2. Even, 12 days after the release of Theia 1.18 there is no new Blueprint version based on it.

One could argue, that Blueprint is still in Beta, but as a plugin developer I need a reference platform to test my plugins with.

**Comment by Jeeppler** [comment]
@marcdumais-work or @vince-fugnitto any updates or news on the topic?

**Comment by marcdumais-work** [comment]
@Jeeppler Good news: CI is fixed as of yesterday. So there a re new packages based on Theia `1.19.0`: https://download.eclipse.org/theia/latest/

**Comment by Jeeppler** [comment]
@marcdumais-work perfect. Thank you.

**Comment by Jeeppler** [comment]
And we even get a Debian package :-)
