### ISSUE TITLE
[EF] clean project download area

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia-blueprint#172]
### Feature Description:

The Foundation is asking that all projects clean-up their download area. For Theia, only Blueprint is up for download. I think we are being asked to remove intermediary versions that are no longer relevant.

Upstream issue:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/78

**Comment by thegecko** [comment]
I have archived all ecd.theia downloads up to 2020, keeping just this year's point releases.

**Comment by marcdumais-work** [comment]
Thanks @thegecko !
