### ISSUE TITLE
Update lerna

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia-blueprint#174]
### Bug Description:
When running `yarn audit` on this repo, 8 out of 11 dependencies with known "high" vulnerabilities, are pulled through `lerna`. We currently use a really old version: `2.11.0` and should update like we did in the main repo.

### Steps to Reproduce:

1. run `yarn audit --level high`
2. Look at how many of these are related to `lerna` (path). e.g.: 
![image](https://user-images.githubusercontent.com/25749063/141135931-71d28a2c-ffe4-4311-a7a9-9c9faa6815f1.png)

### Additional Information

- Operating System:
- Theia Version:

**Comment by vince-fugnitto** [comment]
@marcdumais-work it looks like **dependabot** at least picks them up, but does not display the `path` that lead to the dependency (no mention of lerna), so we still need to investigate a bit further:
- https://github.com/eclipse-theia/theia-blueprint/security/dependabot/yarn.lock/dot-prop/open
