### ISSUE TITLE
AppImage does not show the icon in Linux

### ISSUE THREAD

**Issue by MatthewKhouzam** [eclipse-theia/theia-blueprint#178]
### Steps to Reproduce:

1. Download Blueprint appimage
2. Launch it
3. See the icon in the taskbar

![image](https://user-images.githubusercontent.com/419535/142445568-69fe807b-5033-4fb0-944d-de04a454248c.png)

### Additional Information

- Operating System: Linux, (Ubuntu 18.04) DE: Gnome and Budgie, both fail.
- Theia Version: Version 1.19.0 (Beta)

VS Code API Version: 1.53.2

**Comment by koegel** [comment]
Same here, thanks for reporting!

**Comment by jfaltermeier** [comment]
Linux window icon will be added with https://github.com/eclipse-theia/theia-blueprint/pull/180
