### ISSUE TITLE
Have a way to not show Blueprint welcome screen

### ISSUE THREAD

**Issue by MatthewKhouzam** [eclipse-theia/theia-blueprint#185]
### Feature Description: Do not show welcome screen (Getting Started) again

When refreshing `ctrl`-`r` a workspace, the blueprint splash screen re-appears. It would be good to have a checkbox "don't show this again" on the splash screen. 
It could be re-enabled somehow. (A command maybe?)

**Comment by brianking** [comment]
Do you mean the spinner? I think this is necessary because the alternative is just having a blank screen for a noticeable period of time.

**Comment by koegel** [comment]
@MatthewKhouzam I guess you refer to the "Getting started" view that shows up again? 

![image](https://user-images.githubusercontent.com/1044916/146374329-ed23a01a-0942-4813-b7ef-958145f97f37.png)

**Comment by MatthewKhouzam** [comment]
@koegel got it. The spinner is needed, but this `Getting Started` page comes back at every refresh. (ctrl-r) I was using an unstable plug-in... so it felt like an additional step that could be avoided.
