### ISSUE TITLE
Welcome page tab not marked as active when focused

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia-blueprint#198]
### Bug Description:

The welcome page tab with the label 'Getting started' is not marked as active (stronger contrast of tab label) when it is focus. This is inconsistent to the other views and editors.

### Steps to Reproduce:

![Peek 2022-01-26 18-10](https://user-images.githubusercontent.com/588090/151212189-7a2f042e-2e4c-4b24-9782-02694afdb566.gif)

1. Open welcome page
2. Click on tab and observe tab label
3. Open another editor or view (e.g. preferences) and observe their tab label when focused

### Additional Information

- Operating System: Ubuntu Linux
- Theia Version: 1.21.0 (Beta)

**Comment by koegel** [comment]
Confirmed! If it can be easily fixed, we should go for it, @jfaltermeier.

**Comment by vince-fugnitto** [comment]
For anyone interested you'll need to pass [`activate: true`](https://eclipse-theia.github.io/theia/docs/next/interfaces/core.openviewarguments-2.html) when calling [`openView`](https://eclipse-theia.github.io/theia/docs/next/classes/core.abstractviewcontribution-2.html#openview) for the welcome page, and it will need to implement `onActivateRequest` where it chooses what element in the view should accept the focus.

**Comment by koegel** [comment]
> For anyone interested you'll need to pass [`activate: true`](https://eclipse-theia.github.io/theia/docs/next/interfaces/core.openviewarguments-2.html) when calling [`openView`](https://eclipse-theia.github.io/theia/docs/next/classes/core.abstractviewcontribution-2.html#openview) for the welcome page, and it will need to implement `onActivateRequest` where it chooses what element in the view should accept the focus.

Thank you for the hint, this helps!
