### ISSUE TITLE
[Updater] Error log from updater cannot be opened on Windows due to URI parsing

### ISSUE THREAD

**Issue by xoriath** [eclipse-theia/theia-blueprint#199]
### Bug Description:
#165 introduced the capability to inspect the update log on error. However, due to parsing the path as an URI, the open log action fails on Windows as there are no opener for the URI that is created from the path. The URI has scheme=c and path=path to log file.

### Steps to Reproduce:

1. Check for updates (for instance in a dev session without a correct update yml present)
2. In the error message, click View Log 
3. Nothing happens, console logs 'No resource handler for...'
4. The URI opened contains a percent-encoded version of the Windows path, i.e C:%5CU

### Additional Information

- Operating System: Windows
- Theia Version: [theia-extensions/theia-blueprint-updater/src/common/updater/theia-updater.ts](https://github.com/eclipse-theia/theia-blueprint/commit/7dc31b0969be5f5b27630022fed88759eb41059d#diff-f47195d665f56013fe6c21a99c06526ad3b5d11382c917d09c9d668c0866c6bfR237)

### Fix
Attached patch ([updater-error-path-as-path.txt](https://github.com/eclipse-theia/theia-blueprint/files/7953834/updater-error-path-as-path.txt)) changes the creation of the URI to parse the path as a path directly, instead of using the URI.parse from vscode-uri. This causes the URI to correctly become a file:/// URI that is openable.

**Comment by jfaltermeier** [comment]
Thank you for the report and the hint for the fix. The issue will be fixed with the next release

**Comment by xoriath** [comment]
Thanks @jfaltermeier ! :)
