### ISSUE TITLE
Cannot run signed Theia binary after successful installation on MacOS

### ISSUE THREAD

**Issue by jankeromnes** [eclipse-theia/theia-blueprint#2]
### Bug Description:

I tried installing the new signed Theia binary on my Macbook Pro.

It installed successfully, but when I want to start Theia, it shows me this error message:

<img width="532" alt="Screenshot 2020-08-18 at 16 04 26" src="https://user-images.githubusercontent.com/599268/90523408-219f6300-e16d-11ea-927a-2c70cabdff31.png">

### Steps to Reproduce:

1. Go to https://download.eclipse.org/theia/1.2.0/
2. Click on `macos`
3. Download and open `signed-theia-1.2.0.dmg`
4. Drag the Theia icon onto the Applications icon (installation works)
5. Open Launchpad, find Theia, and try to run it (fails with above error message)

### Additional Information

- Operating System: Mac OS
- Theia Version: 1.2.0

**Comment by vince-fugnitto** [comment]
@jankeromnes I transferred the issue to the following repository, as it is used to create the installers/tracks issues related to the downloads. I hope this is okay!

**Comment by jankeromnes** [comment]
Aha, perfect, many thanks! 👍

**Comment by brianking** [comment]
fyi you can bypass this and manually launch it by going into the macOS security settings.

https://support.apple.com/en-gb/guide/mac-help/mh40616/mac

**Comment by thegecko** [comment]
@jankeromnes We have now completed signing and notarization of the Theia example package which should resolve your issue.

Could you try the latest installers:

https://download.eclipse.org/theia/

**Comment by benoitf** [comment]
there is no .dmg file ?

**Comment by benoitf** [comment]
BTW clicking on the link try to display the binary content 
![download-pkg](https://user-images.githubusercontent.com/436777/96599284-0af1c580-12f0-11eb-892a-933e0004702b.gif)

**Comment by thegecko** [comment]
> there is no .dmg file

No, `.pkg` gives you much more control

> BTW clicking on the link try to display the binary content

Yes, this is an issue with the eclipse download site, patch pending:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=567922

**Comment by koegel** [comment]
I guess this issue can be closed, @thegecko?
