### ISSUE TITLE
Open Folder with preserve window option makes terminals stick to old path

### ISSUE THREAD

**Issue by alimoncul** [eclipse-theia/theia-blueprint#218]
### Bug Description:
While preserve window option is true, opening a folder makes the terminals stick to old path.

### Steps to Reproduce:

1.Open a folder
2.Open a terminal
3.Open different folder
4.See terminal is pointing old folder path.

https://user-images.githubusercontent.com/15328038/168532818-1f6c3fdf-1184-4444-a28b-1c4d985b224c.mp4

- Operating System:
Win11 21H2
- Theia Version:
Eclipse Theia Blueprint
Version 1.25.0 (Beta)
VS Code API Version: 1.53.2

**Comment by jfaltermeier** [comment]
Thank you for the report, I can reproduce it on Linux as well. We will have a look

One addition to the Steps to Reproduce: When opening a folder the window layout for this folder is restored. In order to reproduce the issue, the folder we are switching to, should have had a terminal open before.

**Comment by jfaltermeier** [comment]
The latest version of blueprint contains the upstream theia fix for this issue. 
Please reopen if this is still reproducible with the latest version.
