### ISSUE TITLE
Rename repo to theia-blueprint

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-blueprint#22]
To align with the messaging and the name #19 the repository should also be renamed to theia-blueprint.

**Comment by koegel** [comment]
@thegecko What do you think?

**Comment by thegecko** [comment]
No opinion really :)

**Comment by koegel** [comment]
OK :). @jfaltermeier @JonasHelming What do you think?

**Comment by koegel** [comment]
We (EclipseSource) are working on this on behalf of ST Microelectronics.

**Comment by JonasHelming** [comment]
Yes, i think that would make sense, maybe even "theia-blueprint-product"

**Comment by koegel** [comment]
OK, I think we should go for theia-blueprint then, can you rename the repo, @thegecko ? Does this require changes to the build?

**Comment by thegecko** [comment]
> can you rename the repo, @thegecko

No, in order to make this change, you need to raise an issue with Eclipse for `GitHub`:

https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community

You'll also need to add the owner, @marcdumais-work is that you?

I also recommend you discuss this proposal at a [dev meeting](https://github.com/eclipse-theia/theia/wiki/Dev-Meetings) in case anyone objects.

> Does this require changes to the build?

It could do, again these changes need to be requested through Eclipse issues. I recommend you request access to that CI system in the same way so you can control the builds a little more.

**Comment by koegel** [comment]
> I also recommend you discuss this proposal at a [dev meeting](https://github.com/eclipse-theia/theia/wiki/Dev-Meetings) in case anyone objects.
Good idea to discuss the proposal in the dev meeting, I will do this next Tuesday.
 
> > Does this require changes to the build?
> It could do, again these changes need to be requested through Eclipse issues. I recommend you request access to that CI system in the same way so you can control the builds a little more.
I guess we can only get access to CI for the project once we have committer status

**Comment by marcdumais-work** [comment]
> You'll also need to add the owner, @marcdumais-work is that you?

Webmaster might ask a project lead to +1 the request. If so I can do it (let me know)

**Comment by marcdumais-work** [comment]
> I guess we can only get access to CI for the project once we have committer status

That's my understanding as well. Same for getting write access to the GH repo's wiki, and certain other Eclipse Foundation privileges, like accessing a project's CQs.

**Comment by koegel** [comment]
OK, thanks!

**Comment by brianking** [comment]
> No, in order to make this change, you need to raise an issue with Eclipse for `GitHub`:
> 
> https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community

Has this step happended?

**Comment by marcdumais-work** [comment]
@koegel is correct - access to CI and ability to request project-related help is usually limited to project committers. I registered a quick bugzilla that should do the trick for the repo rename: 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=570920

**Comment by koegel** [comment]
@marcdumais-work Thank you!

**Comment by marcdumais-work** [comment]
The repo has been renamed. 

The old URL will still work (automatic redirect), both in browsers and in git remotes. But it can be a good idea to refer to the new address when possible (e.g. git may warn about it).
