### ISSUE TITLE
Theia Blueprint does not create `extensions` directory

### ISSUE THREAD

**Issue by 0rzech** [eclipse-theia/theia-blueprint#229]
### Bug Description:

Unable to install plugins from Open-VSX. Most likely due to the fact, that Theia Blueprint does not create `.theia-blueprint/extensions` directory. After adding directory manually, the plugin installs fine, though with older version - `23.0.5` instead of `23.0.8` available [here](https://open-vsx.org/extension/AdaCore/ada/23.0.8) (is it because of #96)?

### Steps to Reproduce:

1. Run TheiaBlueprint.AppImage
2. Go to plugins tab.
3. Search for Ada, for example.
4. Click on Install button.

```
root INFO [adacore.ada]: trying to resolve latest version...
root INFO [adacore.ada]: resolved to 'adacore.ada-23.0.5'
root INFO [adacore.ada-23.0.5]: trying to download from "https://open-vsx.org/api/AdaCore/ada/23.0.5/file/AdaCore.ada-23.0.5.vsix"... to path /(...)/.theia-blueprint/extensions
root ERROR Failed to resolve plugins from 'vscode:extension/adacore.ada' Error: ENOENT: no such file or directory, open '/(...)/.theia-blueprint/extensions/AdaCore.ada-23.0.5.vsix'
root INFO Deploy plugin vscode:extension/adacore.ada: 5513.5 ms [Finished 307.119 s after backend start]
root ERROR Request deploy failed with error: Deployment of extension with ID vscode:extension/adacore.ada failed. Error: Deployment of extension with ID vscode:extension/adacore.ada failed.
    at PluginServerHandler.deploy (/tmp/.mount_Theia(...)/resources/app/node_modules/@theia/plugin-ext/lib/main/node/plugin-server-handler.js:41:19)
    at async JsonRpcProxyFactory.onRequest (/tmp/.mount_Theia(...)/resources/app/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:132:24)
    at async RpcProtocol.handleRequest (/tmp/.mount_Theia(...)/resources/app/node_modules/@theia/core/lib/common/message-rpc/rpc-protocol.js:157:28)
root INFO [...] Waiting for backend deployment: 9.7 ms [Finished 305.775 s after frontend start]
root INFO [...] Sync of 0 plugins: 0.3 ms [Finished 305.776 s after frontend start]
root INFO [...] Load contributions of 0 plugins: 0.1 ms [Finished 305.776 s after frontend start]
root INFO [...] Start of 0 plugins: 8.4 ms [Finished 305.799 s after frontend start]
```

### Additional Information

- Operating System: Linux
- Theia Version: 1.28.0

**Comment by vince-fugnitto** [comment]
@0rzech the issue has been fixed upstream in the framework but hasn’t made its way to blueprint yet (https://github.com/eclipse-theia/theia/issues/11485). The workaround as you’ve highlighted is to create the `extensions` folder first (this is usually necessary for new installations).

**Comment by jfaltermeier** [comment]
A new blueprint version was released containing the fix. Please reopen if there is still an issue with the new version.
