### ISSUE TITLE
Change name from theia example to theia blueprint in the code and the config files

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-blueprint#25]
As also pointed out by @marcdumais-work in #19 we need to adapt the name in several places:
- git repo name: see #22 
- packages
   - [Electron App](https://github.com/eclipse-theia/theia-example/blob/master/electron-app/package.json)
      - name: theia-blueprint
      - description: Eclipse Theia blueprint product
      - productName: Theia Blueprint
   - [Updater](https://github.com/eclipse-theia/theia-example/blob/master/theia-example-updater/package.json)
      - name: theia-blueprint-updater",
      - description: Eclipse Theia blueprint product updater
- folder structure: 
   - [electron-app](https://github.com/eclipse-theia/theia-example/tree/master/electron-app): Rename to blueprint-app
   - [theia-example-updater](https://github.com/eclipse-theia/theia-example/tree/master/theia-example-update): Rename to blueprint-updater
- Store user level configurations under user home - ~/.theia-blueprint (rather than the upstream default ~/.theia)

**Comment by koegel** [comment]
@jfaltermeier What is your take on this?

**Comment by marcdumais-work** [comment]
> electron-app: Rename to blueprint-app?

this is the only one I am not sure. If we might offer a packaged browser application from this repo in the future, we can consider keeping the name as-is, and adding a `browser-app` for the new one. An other option is to be a bit more verbose: ` blueprint-electron-app` and ` blueprint-browser-app`.

**Comment by jfaltermeier** [comment]
> @jfaltermeier What is your take on this?

Sounds good. 
Besides the already mentioned places I don't see any other oversights atm.

**Comment by lucas-koehler** [comment]
I like the suggested names. With the main value of this repository being the packaging and updating of the app, which are both electron specific, I think we can assume for now that there won't be a browser app. Or if there ever is, I think we can rename it then? What do you think @marcdumais-work ?

**Comment by koegel** [comment]
> I like the suggested names. With the main value of this repository being the packaging and updating of the app, which are both electron specific, I think we can assume for now that there won't be a browser app. Or if there ever is, I think we can rename it then? What do you think @marcdumais-work ?
> 
> **In any case, we need to make sure to update the documentation accordingly when we do the renames.**
Which suggested names do you refer to @lucas-koehler ?

**Comment by koegel** [comment]
> > electron-app: Rename to blueprint-app?
> 
> this is the only one I am not sure. If we might offer a packaged browser application from this repo in the future, we can consider keeping the name as-is, and adding a `browser-app` for the new one. An other option is to be a bit more verbose: ` blueprint-electron-app` and ` blueprint-browser-app`.

Good points, now I am even more undecided :)

**Comment by lucas-koehler** [comment]
> > I like the suggested names. With the main value of this repository being the packaging and updating of the app, which are both electron specific, I think we can assume for now that there won't be a browser app. Or if there ever is, I think we can rename it then? What do you think @marcdumais-work ?
> > **In any case, we need to make sure to update the documentation accordingly when we do the renames.**
> 
> Which suggested names do you refer to @lucas-koehler ?

I'm referring to the folder names because they are used in the documentation to point users to files that they might want to customize.

**Comment by koegel** [comment]
> > > I like the suggested names. With the main value of this repository being the packaging and updating of the app, which are both electron specific, I think we can assume for now that there won't be a browser app. Or if there ever is, I think we can rename it then? What do you think @marcdumais-work ?
> > > **In any case, we need to make sure to update the documentation accordingly when we do the renames.**
> > 
> > 
> > Which suggested names do you refer to @lucas-koehler ?
> 
> I'm referring to the folder names because they are used in the documentation to point users to files that they might want to customize.

 I know :). But which of the suggested names do you

**Comment by lucas-koehler** [comment]
I see :)
I like `blueprint-app` for the product package (currently in folder electron-app) and `blueprint-updater` for the extension.

I'm also not opposed to the extensive names suggested by @marcdumais-work but do not think they are necessary. Thus, I would rather rename in case this ever comes relevant, which we don't know yet.

**Comment by koegel** [comment]
OK, clarified :). I would say we go with the names I proposed then.

**Comment by koegel** [comment]
@jfaltermeier Can you please take care of the ticket

**Comment by koegel** [comment]
Main remaining problem is the userhome default folder is still .theia.

**Comment by marcdumais-work** [comment]
> Main remaining problem is the userhome default folder is still .theia.

I think we can contribute an incremental improvement, that permits to override this with a static string e.g. a product name. In our case the folder could be named `.blueprint`. 

It will be helpful for ourselves to do so, because right now the Blueprint config folder is shared with that of vanilla Theia applications, including our own example application. No good can come of this :)

cc: @vince-fugnitto
