### ISSUE TITLE
[CI] [Jenkins] Clean-up tmp files on Windows agent after CI run

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia-blueprint#256]
### Bug Description:
It seems that temporary files, left on the Windows agent, caused it to run out of disk space and require human intervention [1] : 

_"I've liberated a whopping 40GB of diskspace from Eclipse Theia's temp folder on the Windows agent (mp23n-windows-10). 🙈
please try to make sure that temporary files are properly deleted after they are no longer used."_

It's possible that cleaning-up for other OS than Windows would be desirable, too. 

\[1\]: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2858#note_1095949

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System:
- Theia Version:

**Comment by marcdumais-work** [comment]
@jfaltermeier would you be willing to have a look at this issue?

**Comment by jfaltermeier** [comment]
Yes, I can have a look. It might be a yarn issue: https://github.com/yarnpkg/yarn/issues/6685
I don't think we create temp files ourselves that we forget to clean up.

**Comment by marcdumais-work** [comment]
We should be good to close this issue. @jfaltermeier, has the new Jenkinsfile, that does the cleanup on windows agent, been configured to run periodically? e.g. every week or day?

**Comment by jfaltermeier** [comment]
It is configured to run periodically if not otherwise run, every 1 week.

**Comment by marcdumais-work** [comment]
Thanks for the help @jfaltermeier . After this, I now know that the Windows temp we use is one that's specific to our project. So, if this were to start to fail for some reason, I would suggest we do a version that e.g. deletes everything under that folder, that's older than x days - e.g. a week (unlikely to still be in-use by then).
