### ISSUE TITLE
@electron/remote removed in next Theia version

### ISSUE THREAD

**Issue by jfaltermeier** [eclipse-theia/theia-blueprint#258]
### Bug Description:

`@electron/remote` will be removed with the next theia version: https://github.com/eclipse-theia/theia/issues/2018
We have to adapt our code accordingly. 

### Steps to Reproduce:

1. Update to next version
2. Try to build

**Comment by jfaltermeier** [comment]
I will prepare this on the next branch and integrate it after the Theia Release

**Comment by jfaltermeier** [comment]
> It's not easy, I try to upgrade1.37.0 but failed, hope you can make it right.

I will try to update the main branch on Tuesday. 
In the meantime, you may have a look at this commit: https://github.com/eclipse-theia/theia-blueprint/commit/edfdfcc3eaa014aed7c77067e883b3c18d7a67d2

**Comment by ouliuquan** [comment]
Thank you, very kind of you, I will try this commit soon.
