### ISSUE TITLE
Add all vscode built-ins

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-blueprint#26]
Adding all built-ins will improve compatibility with vscode extensions that are potentially installed by users. For a list see this [package.json](https://github.com/eclipse-theia/theia/blob/master/package.json#L86-L154).

This was an idea of @marcdumais-work, see comment [here](https://github.com/eclipse-theia/theia-example/issues/5#issuecomment-762369667_).

**Comment by jfaltermeier** [comment]
We removed markdown-language-features for now, because the compatible version was removed from open-vsx.
Readd this as part of this task

**Comment by marcdumais-work** [comment]
I'm working on providing a working replacement for the markdown-language-features extension, and publishing it on open-vsx programmatically. See: https://github.com/eclipse-theia/vscode-builtin-extensions/issues/14#issuecomment-772627682

**Comment by marcdumais-work** [comment]
`markdown-language-features` v1.39.2 has been re-published to `open-vsx.org`. You could re-add it for `Blueprint`

**Comment by koegel** [comment]
#81 is related
