### ISSUE TITLE
Electron can't download update.

### ISSUE THREAD

**Issue by hyy215** [eclipse-theia/theia-blueprint#273]
### Bug Description:
Electron can't download update.

### Steps to Reproduce:

1. Download and install 1.37.0.
2. Choose `yes` to update.
3. Always waiting for downloading.
![7e6605c6ac0b9c6a40bcaa036f1dcb3](https://github.com/eclipse-theia/theia-blueprint/assets/34715914/9734a700-0882-4000-b84d-d965a8e480e1)

https://github.com/eclipse-theia/theia-blueprint/blob/5fe2d301210a4e4fdde8e5eb91a25988214cacbf/theia-extensions/theia-blueprint-updater/src/electron-browser/updater/theia-updater-frontend-contribution.ts#L33
https://github.com/eclipse-theia/theia-blueprint/blob/5fe2d301210a4e4fdde8e5eb91a25988214cacbf/theia-extensions/theia-blueprint-updater/src/electron-browser/updater/theia-updater-frontend-contribution.ts#L188-L208

`nodeIntegration: false` in theia default config.
Beginning in Electron 20, renderers will be sandboxed by default and preload scripts hadn't access to Node.js.
https://www.electronjs.org/blog/electron-20-0#default-changed-renderers-without-nodeintegration-true-are-sandboxed-by-default

### Additional Information

- Operating System: win10
- Theia Version: 1.37.0

**Comment by jfaltermeier** [comment]
Thank you for the report, I will have a look at fixing this in the next days
