### ISSUE TITLE
The 1.38.0 app is 100Mb larger than the previous releases

### ISSUE THREAD

**Issue by kittaakos** [eclipse-theia/theia-blueprint#274]
### Bug Description:

I have noticed that the blueprint app size has grown by 100Mb between 1.37 and 1.38.

<img width="691" alt="Screenshot 2023-06-22 at 09 19 06" src="https://github.com/eclipse-theia/theia-blueprint/assets/1405703/be5183f5-0db1-4c8d-a468-974e32d04693">

### Steps to Reproduce:

1. Compare the latest (1.38.0) release with previous ones.
2.
3.

### Additional Information

- Operating System: macOS
- Theia Version: 1.38

**Comment by thegecko** [comment]
> maybe it would make sense to be a big more generic and only bundle vscode built-ins?

IMO, keeping the blueprint simple is preferable over trying to support everything. We could always add different flavours in future as required (e.g. java blueprint).

**Comment by JonasHelming** [comment]
@jfaltermeier @koegel

**Comment by marcdumais-work** [comment]
@kittaakos here is an updated screenshot with plugins ordered by size, which makes it a bit easier to read I think:

![Screenshot from 2023-06-22 10-42-14](https://github.com/eclipse-theia/theia-blueprint/assets/25749063/705eb0f7-401a-4e0b-8c44-fb98a0c0d46b)

**Comment by kittaakos** [comment]
> That's installed size, I believe?

Yes, the installed size. It's the unpacked application size on macOS.

> This does not necessarily mean that anything is abnormal with the plugins. Rather, for 1.38, we refreshed some of them for the first time in a long while.

> here is an updated screenshot with plugins ordered by size, which makes it a bit easier to read I think:

Thanks a lot for your time in creating the report. The numbers add up, so it's not a flaw in the app bundling.
I wanted to download the latest version to see the manifestation of https://github.com/eclipse-theia/theia/pull/12412, but I have just noticed it's scheduled for `1.39.0`, I was an idiot.

Feel free to close this as not a bug.

**Comment by StellarH** [comment]
Perhaps it needs to be like eclipse, provide theia with different plugins built in for different developer types and a minimize package.
