### ISSUE TITLE
Theia welcome page shows after each restart

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia-blueprint#277]
### Bug Description:
The Theia welcome page (editor) is shown each time I start Blueprint. My expectation would be that the page only shows the first time or after an update has been installed.

### Steps to Reproduce:

1. Start Blueprint (you get the Welcome page)
2. Quit Blueprint
3. Start Blueprint (you get the Welcom page again.

### Additional Information

- Operating System: Windows
- Theia Version: Blueprint 1.39.0

**Comment by tsmaeder** [comment]
![image](https://github.com/eclipse-theia/theia-blueprint/assets/13163770/7cb81a24-d0de-4d73-adff-3bf988d3c5db)

**Comment by vince-fugnitto** [comment]
@tsmaeder if you have the preference on (from the screenshot it looks to be "checked") then each start of the application will open the welcome page if no editor is opened. The same behavior can be identified in VS Code.

**Comment by tsmaeder** [comment]
Indeed, that fixes the problem. I wonder, though, why this is on by default. I noticed that there is a "Show Welcome Page after every start of the application" check box at the bottom of the welcome page. But t.b.h., I didn't read this far down, and the check box disappears when the editor is too small. IMO, the "don't nag me"-UI should be more prominent.

**Comment by tsmaeder** [comment]
Since this works as designed, I'm closing this one in favor of a feature request: https://github.com/eclipse-theia/theia-blueprint/issues/280
