### ISSUE TITLE
Include secondary window support in Blueprint

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-blueprint#284]
Now that the support for detachable views (secondary window support) is available for Electron, we should include it in Blueprint.
As a follow up, it would be nice to have it in CDT Cloud Blueprint, too.
@jfaltermeier

**Comment by jfaltermeier** [comment]
The package is included in blueprint: https://github.com/eclipse-theia/theia-blueprint/blob/11d299b22db9298ba7915c14040d55a5e5491bec/applications/electron/package.json#L74
So terminals and webviews can be moved to a secondary window.
