### ISSUE TITLE
No Window Icon 

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia-blueprint#288]
### Bug Description:
Theia Blueprint does not have an icon (Application icon) on the top left corner on Windows. This works in the Electron example project in Theia.

### Additional Information

- Operating System: Win 11
- Theia Version: 1.39.0

**Comment by JonasHelming** [comment]
At the same time we should also add a favicon: https://github.com/eclipse-theia/theia/issues/3600#issuecomment-808747788
