### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-theia/theia-blueprint#291]
### Bug Description:
I cannot update from 1.39.0 to 1.40.0: the update does not finish

### Steps to Reproduce:

1. Have blueprint 1.39.0 installed
2. A while after the start, a notification occurs, announcing that an update is available
3. Click "Yes" on the notification
4. Observe: a unknown progress indicator appears on the notification, but stays forever, not doing anything

### Additional Information

When clicking yes, this exception occurs in the browser log:
```
theia-updater-frontend-contribution.ts:200 Uncaught (in promise) TypeError: (0 , u.setInterval) is not a function
    at A.handleDownloadUpdate (theia-updater-frontend-contribution.ts:200:31)
handleDownloadUpdate @ theia-updater-frontend-contribution.ts:200
await in handleDownloadUpdate (async)
(anonymous) @ theia-updater-frontend-contribution.ts:149
(anonymous) @ event.ts:128
invoke @ event.ts:136
fire @ event.ts:279
(anonymous) @ theia-updater-frontend-contribution.ts:86
```

- Operating System:
- Theia Version:

**Comment by jfaltermeier** [comment]
This should be fixed starting with 1.40 with https://github.com/eclipse-theia/theia-blueprint/pull/285

**Comment by JonasHelming** [comment]
@tsmaeder Could you validate the fix, please?

**Comment by jfaltermeier** [comment]
The fix is not released yet, because the build fails on windows. The Machine has too few RAM available. I've reopened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3231 but there was no reply yet

**Comment by jfaltermeier** [comment]
1.41 is released now. 
Updating from 1.40 (https://download.eclipse.org/theia/1.40.0/) to 1.41 worked for me on windows and linux. I don't have a mac available.
