### ISSUE TITLE
Should we add actions to the welcome page

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-blueprint#30]
Like the default welcome page provides (recent workspaces, open file, etc..)

![image](https://user-images.githubusercontent.com/1052615/106355877-2ca11680-62fb-11eb-81d1-13918c52a93b.png)

**Comment by koegel** [comment]
What would be easy is to just add exactly the same actions as on the Theia default page below the blueprint default welcome page, this would mean it will scroll. What do you think, @JonasHelming ?

**Comment by vince-fugnitto** [comment]
> What would be easy is to just add exactly the same actions as on the Theia default page below the blueprint default welcome page, this would mean it will scroll. What do you think, @JonasHelming ?

@koegel I have not followed the discussion or motivation behind the current `getting-started` page closely, however, I believe the information it provides is likely only useful the first time the application is ever started, and not each time the app is started without a workspace. The default `getting-started` (upstream) is more useful day-to-day as it provides developers with information, and actions (recent workspaces, commands, preferences, etc.).

Perhaps the disclaimer and information present in the current `getting-started` would be more appropriate in its own widget, or solely in the documentation (readme or website). I understand that this page is likely the first to get updated however, but I'm sure we would want users to use `blueprint` in the long-run as well and we would want to target a good experience.

**Comment by koegel** [comment]
I have a different opinion on this. For now Theia Blueprint is only for showcasing the Theia platform feature set and for enabling developers to try it. I am not comfortable with them using it in production on a daily basis, since we are not testing for this scenario (not manually and no automated tests) and have no capacity to do so. So imho the welcome page is a constant reminder of the purpose of Theia Blueprint.

**Comment by koegel** [comment]
I believe we should be really careful in the beginning with how we communicate the purpose of Theia Blueprint initially to avoid over promising and to avoid damage to the trust in the Theia platform. But this is just my opinion.

**Comment by vince-fugnitto** [comment]
@koegel I see! Thank you for clarifying its purpose for the moment, it's always something we can update in the future 😄 Note that the way the `getting-started` works is that it is displayed when no workspace is present, did you want to display it each time the `blueprint` app is started until we are more comfortable?

**Comment by koegel** [comment]
Yes, exactly, when we build more trust we could easily shift the messaging.

**Comment by koegel** [comment]
Good point about the welcome page. Is there a simple way to show it also if no workspace is present?

**Comment by vince-fugnitto** [comment]
> Good point about the welcome page. Is there a simple way to show it also if no workspace is present?

@koegel if you want to customize the behavior you will need to override the current `onStart` method:

- https://github.com/eclipse-theia/theia/blob/22dcd7e2c9bd8dc8774d83f5b1ab78d980cfd76e/packages/getting-started/src/browser/getting-started-contribution.ts#L51-L57
