### ISSUE TITLE
[CI] Latest PR merged seems to have triggered wrong Jenkins job?

### ISSUE THREAD

**Issue by marcdumais-work** [eclipse-theia/theia-blueprint#306]
### Bug Description:
Looking at the repo's latest commits, I saw that a PR was merged on Sept 29th and that CI was successful (green checkmark). However, looking at [packages available for download](https://download.eclipse.org/theia/latest/linux/), none seem to be from around that date. 

Then I noticed that the Jenkins job that's associated to the latest commit is the wrong one (click on the green checkmark next to the commit, then click on "details" next to "continuous-integration/jenkins/br...". 

The link leads [here](https://ci.eclipse.org/theia/job/Theia%20-%20Cleanup%20Build%20Nodes/job/master/43/) (Theia - Cleanup Build Nodes job)

![image](https://github.com/eclipse-theia/theia-blueprint/assets/25749063/3a05dd9b-123c-4496-8a54-93dc3567ff1e)

Should it not instead lead to this job, and be marked as failed?
![image](https://github.com/eclipse-theia/theia-blueprint/assets/25749063/b290f5f5-4cca-4c39-a97e-e3f46794da66)

![image](https://github.com/eclipse-theia/theia-blueprint/assets/25749063/a17db9ef-2b98-4668-a616-94abb035b9f6)

### Steps to Reproduce:

1.
2.
3.

Latest commits in the repo:
![image](https://github.com/eclipse-theia/theia-blueprint/assets/25749063/0e5a4176-cd4f-4ad5-a23e-7fb1cf1bdbae)

After-PR-merged CI: from the main repo page, click on the green checkmark next to latest commit (79e6c3c) or go to the "commits" page and do the same.
![image](https://github.com/eclipse-theia/theia-blueprint/assets/25749063/895f079e-a95b-4e85-a80b-47e18e3de833)

### Additional Information

- Operating System:
- Theia Version:

**Comment by marcdumais-work** [comment]
cc: @jfaltermeier

**Comment by jfaltermeier** [comment]
The build that was triggered by this merge was https://ci.eclipse.org/theia/job/Theia2/job/master/124/
I aborted this one, because I was working on the 1.42 Update (https://github.com/eclipse-theia/theia-blueprint/pull/305), which I wanted to base on the welcome page PR, and expected to be finished soon. 
I did not expect that there will be an issue with 1.42.0 production builds.  
So that this PR is not released yet is my fault. 
We should check if aborting the job also somehow caused this mixup with the green checkmark.

**Comment by marcdumais-work** [comment]
> We should check if aborting the job also somehow caused this mixup with the green checkmark.

That's the part that I am/was worried about - really weird. 

> I did not expect that there will be an issue with 1.42.0 production builds.

Ok, let's see what happens next time a PR is merged, and confirm that the correct Jenkins job is triggered?

**Comment by jfaltermeier** [comment]
The last commit points to the right Jenkins job now.
