### ISSUE TITLE
Renamed directory paths in `browser.Dockerfile`

### ISSUE THREAD

**Issue by goekce** [eclipse-theia/theia-blueprint#309]
I am creating a package for deployment using `browser.Dockerfile`. I noticed that some paths mentioned here:

https://github.com/eclipse-theia/theia-blueprint/blob/c70b99f6fed23cf6ee4ca9105b93c761f808630b/browser.Dockerfile#L26

do not exist. `theia-blueprint-launcher` and `theia-blueprint-updater` seem to be renamed to `launcher` and `updater`. If true, I can create a PR.

**Comment by marcdumais-work** [comment]
Hi @goekce ,

Yes, I think it was an oversight, not to update those paths in `browser.Dockerfile`. A PR is welcome!
