### ISSUE TITLE
Proposal to Relicense Theia Blueprint to MIT: Seeking Approvals

### ISSUE THREAD

**Issue by planger** [eclipse-theia/theia-blueprint#310]
👋 Hey all,

In our last Theia Dev call, we reached a consensus on considering a change of license for the [Theia Blueprint project](https://github.com/eclipse-theia/theia-blueprint). We're thinking of moving from [EPL 2.0](https://github.com/eclipse-theia/theia-blueprint/blob/master/LICENSE) (or [GNU General Public License with classpath exception](ttps://www.gnu.org/software/classpath/license.html)) to [MIT](https://opensource.org/license/mit/). As Theia Blueprint is meant to be an example as well as a template for adopters, the aim is to clear up any gray areas around the reuse and modification of the Blueprint code in proprietary projects.

This should make it easier for everyone to adopt and modify Blueprint without worrying over the current [licensing complexities](https://www.eclipse.org/legal/epl-2.0/faq.php#h.xu4ooq8g5mx8). Note that this is only about the code contained in this repository (Theia Blueprint), not Theia in general.

## What We Need

To officially make this change, we need a thumbs-up ("+1") from a representative of every copyright holder who has contributed to Theia Blueprint.

Please reply to this issue with a +1 if you're on board with this license change.

If you have any concerns or questions, feel free to comment on this issue or reach out to us directly.

Thanks for your cooperation! 🙏

## More information

* [Help desk ticket at the Eclipse Foundation](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3875)
* [Approval from the Eclipse Foundation](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3875#note_1264006) to use MIT for [Non-Code, Example, and Other Content](https://www.eclipse.org/legal/noncodelicenses.php)

## List of [contributors](https://github.com/eclipse-theia/theia-blueprint/graphs/contributors)

- [x] @thegecko
- [x] EclipseSource (@jfaltermeier, @lucas-koehler, @AlexandraBuzila, @JonasHelming, @tortmayr)
- [x] Ericsson (@marcdumais-work, @vince-fugnitto, @paul-marechal)
- [x] @danepowell
- [x] STMicroelectronics (@Niklas-Dahlquist, @ErikMallbergSTM)
- [x] @Atharva321
- [x] @duncdrum
- [x] TypeFox (@msujew)
- [x] @DucNgn

**Comment by planger** [comment]
+1

**Comment by thegecko** [comment]
+1

**Comment by JonasHelming** [comment]
+1

**Comment by Niklas-Dahlquist** [comment]
+1 from STMicroelectronics (@ErikMallbergSTM and @Niklas-Dahlquist)

**Comment by tortmayr** [comment]
+1

**Comment by MatthewKhouzam** [comment]
I have checked with Ericsson, we all approve the re-licensing.  (Marc D, Paul M, Duc and Vince F) Please confirm Duc did not contribute after 2021.

**Comment by planger** [comment]
@Atharva321 Please let me know what you think about our plans for re-licensing Theia Blueprint (see above). Thank you!

**Comment by Atharva321** [comment]
+1

**Comment by srl295** [comment]
the README still says EPL/GPL

**Comment by JonasHelming** [comment]
Thanks for reporting, see: https://github.com/eclipse-theia/theia-ide/pull/415
