### ISSUE TITLE
Content Updates to About / Welcome

### ISSUE THREAD

**Issue by brianking** [eclipse-theia/theia-blueprint#32]
@croundy and I have made a pass through the text and have some minor suggestions. The main one is not using the term 'Eclipse Theia Blueprint product' andf replacing it with just 'Eclipse Theia Blueprint'.

PR to follow.

**Comment by koegel** [comment]
Thanks, sounds good to me, I already commented on the PR.

**Comment by koegel** [comment]
@brianking Issue can be closed, right? If so please go ahead and close the issue. Thanks!
