### ISSUE TITLE
Theia Blueprint still contains Theia git extension

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-blueprint#320]
When I open the SCM view in Theia Blueprint, I BELIEVE, it still shows the Theia Git extension and not the build in. For example, if I navigate to a folder with no git repo, it shows "no repository found" while the VS Code extension shows two buttons and allow to initialize a repo. Could this be?

- Operating System: Linux
- Theia Version: 1.44

**Comment by jfaltermeier** [comment]
`@theia/git` does not appear in yarn.lock, so I think we only have vscode.git available. 
The "no repository found" comes from `@theia/scm` which is also required by `@theia/plugin-ext`.
