### ISSUE TITLE
Linux download link is broken

### ISSUE THREAD

**Issue by dpetroff** [eclipse-theia/theia-blueprint#329]
### Bug Description:
Linux download link is broken.

### Steps to Reproduce:

1. https://theia-ide.org/#theiaidedownload
2. Pick the Linux option.
3. 
![image](https://github.com/eclipse-theia/theia-blueprint/assets/1384881/e601e81e-db66-4833-8fdc-273585248b39)

### Additional Information

- Operating System: Linux
- Theia Version: N/A

**Comment by jfaltermeier** [comment]
Thanks for the report. The link should be fixed now. If you get a 404 a mirror might not have picked up the change yet.
