### ISSUE TITLE
Measure number of downloads

### ISSUE THREAD

**Issue by brianking** [eclipse-theia/theia-blueprint#36]
This may already happen automatically for files hosted on Eclipse infrastructure, but I want to make sure we are aware of this and tracking from the start. It'll be one of the most important metrics on the success of the project.

**Comment by brianking** [comment]
Related question, will releases still be listed on this page: https://download.eclipse.org/theia/

I know we will also have a download page on https://theia-ide.org.

**Comment by waynebeaton** [comment]
Start [here](https://wiki.eclipse.org/IT_Infrastructure_Doc#Downloads).

**Comment by brianking** [comment]
Thanks, linked therein is https://wiki.eclipse.org/Project_Download_Stats.

@thegecko Have we already been tracking?

**Comment by thegecko** [comment]
> @thegecko Have we already been tracking?

Not unless recorded by the eclipse download systems

> will releases still be listed on this page?: https://download.eclipse.org/theia/

That's where they are currently published, I'm not aware of any plan to change that.

> I know we will also have a download page on https://theia-ide.org.

Perhaps just redirect from there to https://download.eclipse.org/theia/?

**Comment by brianking** [comment]
> Perhaps just redirect from there to https://download.eclipse.org/theia/?

I propose we have buttons on the page that link directly to the latest versions of the installers.

Then we can perhaps have a 'See all versions' link that goes to https://download.eclipse.org/theia/

**Comment by koegel** [comment]
@jfaltermeier Can you please comment on this. We have addressed this as part of #7.

**Comment by jfaltermeier** [comment]
> @jfaltermeier Can you please comment on this. We have addressed this as part of #7 imho.

Right, so on the download page we will use links using the eclipse foundation's mirror redirector as mentioned here: https://wiki.eclipse.org/IT_Infrastructure_Doc#See_download_statistics.3F
https://wiki.eclipse.org/Project_Download_Stats
This is in place on the proposed download page

Regarding tracking updates we thought about hitting e.g. https://download.eclipse.org/theia/latest/latest.yml (or some other dedicated file) using the mirror redirector after the user accepted to download the update. 
This way the electron-updater may still use the direct link and we can track updates as well. 

We may then check statistics at https://dev.eclipse.org/committers/committertools/stats.php

**Comment by koegel** [comment]
> > @jfaltermeier Can you please comment on this. We have addressed this as part of #7 imho.
> 
> Right, so on the download page we will use links using the eclipse foundation's mirror redirector as mentioned here: https://wiki.eclipse.org/IT_Infrastructure_Doc#See_download_statistics.3F
> https://wiki.eclipse.org/Project_Download_Stats
> This is in place on the proposed download page
> 
> Regarding tracking updates we thought about hitting e.g. https://download.eclipse.org/theia/latest/latest.yml (or some other dedicated file) using the mirror redirector after the user accepted to download the update.
> This way the electron-updater may still use the direct link and we can track updates as well.

This is not done yet, is it?

**Comment by jfaltermeier** [comment]
> > Regarding tracking updates we thought about hitting e.g. https://download.eclipse.org/theia/latest/latest.yml (or some other dedicated file) using the mirror redirector after the user accepted to download the update.
> > This way the electron-updater may still use the direct link and we can track updates as well.
> 
> This is not done yet, is it?

Not yet

**Comment by brianking** [comment]
Any updates about this feature?

**Comment by jfaltermeier** [comment]
> Any updates about this feature?

With https://github.com/eclipse-theia/theia-blueprint/pull/56 we have regular stable download links for which we will track the downloads. 

With https://github.com/eclipse-theia/theia-blueprint/pull/66 we will also record the number of total updates

**Comment by vince-fugnitto** [comment]
> With #56 we have regular stable download links for which we will track the downloads.
> 
> With #66 we will also record the number of total updates

@jfaltermeier with the two pull-requests referenced being merged, is there anything missing before the issue can be closed?

**Comment by jfaltermeier** [comment]
@vince-fugnitto Everything is in place, I'll close this issue. 
Stats may be checked at https://dev.eclipse.org/committers/committertools/stats.php e.g. with search query `/theia/latest/%`
