### ISSUE TITLE
Add AI Support

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-blueprint#398]
In the upcoming 1.54 release, we will include the experimental AI support in the Theia IDE.
Please add the respective packages and the section on the welcome page (see https://github.com/eclipse-theia/theia/blob/5b078191db626a01741047d0d5056a3569c54d1a/packages/getting-started/src/browser/getting-started-widget.tsx#L405)
just below documentation.

Include: OpenAI, VLLM and Ollama (no LLamaFile for now)

**Comment by JonasHelming** [comment]
@sgraband Is this done?

**Comment by sgraband** [comment]
Will be closed by https://github.com/eclipse-theia/theia-blueprint/pull/402

**Comment by sgraband** [comment]
Closed by #402
