### ISSUE TITLE
When scroll down from NPM to Preview in setting page, it automatically jump up to Extensions

### ISSUE THREAD

**Issue by PassingByThs** [eclipse-theia/theia-blueprint#404]
### Steps to Reproduce:

1.  Open Setting page and scroll down in the right.
2.  When scroll down from NPM to Preview, it automatically jump up to Extensions.

![recording](https://github.com/user-attachments/assets/140bfbb9-95d2-4054-bc2a-79facf40e745)

### Additional Information
- Operating System:
![图片](https://github.com/user-attachments/assets/378cda01-4c7f-4258-b942-d4653ac97b38)

- Theia Version:
![图片](https://github.com/user-attachments/assets/779da300-c099-470f-b4ff-63c59b17b666)

**Comment by PassingByThs** [comment]
I uninstall and install extentions one by one. It seems after installed [Project Manager](https://open-vsx.org/extension/alefragnani/project-manager) , this issue happends.

**Comment by JonasHelming** [comment]
> I uninstall and install extentions one by one. It seems after installed [Project Manager](https://open-vsx.org/extension/alefragnani/project-manager) , this issue happends.

Thank you for the details. I installed the project manager, but for me it works fine, i.e. I cannot reproduce this. I am on Linux, though and on Theia 1.54

**Comment by PassingByThs** [comment]
After updated to Theia 1.54.0, it has been solved.
