### ISSUE TITLE
GLIBC on build machine too recent for Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by jfaltermeier** [eclipse-theia/theia-blueprint#41]
### Bug Description:
When starting the AppImage on Ubuntu 18.04 we get this error:
```
Failed to start the backend application.
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_Theia-cDpToP/resources/app/node_modules/@theia/node-pty/build/Release/pty.node)
```

### Steps to Reproduce:

1. Start the AppImage on Ubuntu 18.04 LTS

**Comment by jfaltermeier** [comment]
As far as I could see using `FROM node:12.19.0-stretch` instead of  `FROM node:12.19.0-buster` in https://github.com/eclipse-theia/theia-blueprint/blob/master/Dockerfile should work. 
@thegecko Is there a dependency to buster or can we use stretch on the Build-Server for building the Linux related bits?

**Comment by thegecko** [comment]
> Is there a dependency to buster

not AFAIK

**Comment by marcdumais-work** [comment]
On which OS was the `AppImage` built? More recent than Ubuntu 18.04? 

`AppImage` is a very useful format, but it has its limitations. Practically I find that what's more likely to work is to build the `AppImage` on the oldest OS possible, so as not to depend on anything that will not be present, if you attempt to run it on an older machine.

Example: I have two machines:
1- Ubuntu 20.04
2- RHEL/CentOS 7.x (oldest on which Theia apps are known to work)

If I build the `Appimage` on 1, it will not work on 2 or probably anything older than 1. If I build it on 2, it will likely work ok on 1.

**Comment by jfaltermeier** [comment]
The Linux build is done like this:
https://github.com/eclipse-theia/theia-blueprint/blob/850fe09f304bd1ca23edf58545f8df97c2272388/Jenkinsfile#L17

So we are using the thegecko/theia-dev image to build, which is built from https://github.com/eclipse-theia/theia-blueprint/blob/master/Dockerfile as far as I could see. So currently this is Debian Buster

If we deploy a new version of this image using the Dockerfile from https://github.com/eclipse-theia/theia-blueprint/pull/46 we should have compatibility with more Unix Versions.

**Comment by thegecko** [comment]
FYI `thegecko/theia-dev` is simply a published version of:

https://github.com/eclipse-theia/theia-blueprint/blob/master/Dockerfile.

It should probably be published somewhere else. Anyone aware of a docker registry owned by Theia or Eclipse we can use?

**Comment by jfaltermeier** [comment]
> Yes, `thegecko/theia-dev` is simply a published version of:
> 
> https://github.com/eclipse-theia/theia-blueprint/blob/master/Dockerfile.
> 
> It should probably be published somewhere else. Anyone aware of a docker registry owned by Theia or Eclipse we can use?

I found this in the eclipse project handbook: https://wiki.eclipse.org/CBI#Docker_Hub
So it should be possible for committers to publish under the eclipse organization once requested

**Comment by marcdumais-work** [comment]
Let's just be aware of this limitation. We might eventually consider adding OS-specific builds to improve compatibility: e.g. RHEL7+, Ubuntu LTS, ...

**Comment by thegecko** [comment]
> ...we should consider creating the next generation of "theia-apps" under the foundation

Yeah, good idea. My only concern would be the effort to produce these and ongoing maintenance. How do we ensure they don't rot?

To solve this issue of hosting the linux build machine (and considering the potential future images you suggest), should we request an `eclipseTheia` organisation as outlined on https://wiki.eclipse.org/CBI#Docker_Hub

**Comment by marcdumais-work** [comment]
>  How do we ensure they don't rot?

I guess the same way we do for images under [theia-apps](https://github.com/theia-ide/theia-apps): have a minimal test suite that detects if the image is borked and generally maintain them. @vince-fugnitto  and myself have been doing most of that work (not a huge effort), and we could transition to the new images. The idea would be to do them from scratch or at least not based on our existing images.

**Comment by marcdumais-work** [comment]
> To solve this issue of hosting the linux build machine (and considering the potential future images you suggest), should we request an eclipseTheia organisation as outlined on https://wiki.eclipse.org/CBI#Docker_Hub

sounds like a good idea!

**Comment by thegecko** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=571598
