### ISSUE TITLE
Cannot find module "fix-path"

### ISSUE THREAD

**Issue by nimo23** [eclipse-theia/theia-blueprint#57]
### Bug Description:
I downloaded https://download.eclipse.org/theia/latest/macos/, installed it and when clicking the app, it does not start, the following error is shown:

![Screenshot at Mar 19 14-46-32](https://user-images.githubusercontent.com/3045549/111790983-11966000-88c3-11eb-89d1-474b13e18535.png)

### Steps to Reproduce:

1. Install https://download.eclipse.org/theia/latest/macos/
2. Start app

### Additional Information

- Operating System: mac os 10.14.6
- Theia Version: TheiaBlueprint-1.11.0.pkg

**Comment by vince-fugnitto** [comment]
@nimo23 thank you for the report, I moved the issue to the appropriate repository. 
I believe the issue has been recently fixed: https://github.com/eclipse-theia/theia-blueprint/issues/52, https://github.com/eclipse-theia/theia-blueprint/pull/53.

**Comment by nimo23** [comment]
Thanks.
