### ISSUE TITLE
git: consider switching to builtin extensions

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia-blueprint#61]
#### Feature Description:

We should consider switching to using the **vscode builtins** for **git** support for the application rather than `@theia/git`.

Some considerations for switching over:
- buitin git support is feature rich, and provides a closer experience to vscode.
- the `@theia/timeline` extension is useless without it, `@theia/git` does not register timeline providers (ex: _git history_).
- including the builtin is necessary in order to use other git-related extensions such as the popular `gitlens`.

#### Builtins:

- [vscode-builtin-git](https://open-vsx.org/extension/vscode/git)
- [vscode-builtin-git-ui](https://open-vsx.org/extension/vscode/git-ui)

**Comment by marcdumais-work** [comment]
This is something we have done quite a while ago in our internal Theia-based app. We think it's the way to go and would like to upstream this to Blueprint, among other things.

**Comment by marcdumais-work** [comment]
See for example this [issue](https://github.com/theia-ide/theia-apps/issues/474), where cloning a repo from the IDE (not terminal) does not work, when credentials are needed. The same should work OOTB with the vscode-builtin git.
