### ISSUE TITLE
Install location on macOS has redundant folder

### ISSUE THREAD

**Issue by brianking** [eclipse-theia/theia-blueprint#62]
### Bug Description:

Theia installs in the location:
Applications -> Theia -> Theia.app

I would expect it to be just:
Applications -> Theia.app

One of the side effects is that the app doesn't appear to be indexed for system search until it is opened, although that could be a latency issue related to my system.

### Steps to Reproduce:

1. Install Blueprint

### Additional Information

- Operating System: macOS Big Sur 11.2.3
- Theia Version: 1.11.0

**Comment by vince-fugnitto** [comment]
@brianking is this still an issue? I downloaded and installed `blueprint` today (on macOS) and I got the following:

```
/Users/vincentfugnitto/Applications/TheiaBlueprint.app
```

**Comment by brianking** [comment]
Not an issue. I removed the current folder+application and installed fresh from the package. This time there is no extra folder. Closing.
