### ISSUE TITLE
Move Check for Updates to application menu

### ISSUE THREAD

**Issue by brianking** [eclipse-theia/theia-blueprint#70]
macOS.

Currently it is in File -> Settings ->

On macOS the standard is for it to go in the application menu, i.e. TheiaBlueprint, which is the first menu.

**Comment by koegel** [comment]
To me it seems that withouta fix in Theia of https://github.com/eclipse-theia/theia/issues/6497 it does not make sense to fix this bug.

**Comment by brianking** [comment]
Or vice versa? Once we figure out how to do one, it should be straightforward to do the other.

**Comment by koegel** [comment]
This issue is a duplicate of  https://github.com/eclipse-theia/theia/issues/6497 and would be automatically be fixed once a new Theia version including the fix integrated into Blueprint. 
@jfaltermeier Can you please close it.
