### ISSUE TITLE
Check for Updates gives no feedback if there is none [macOS]

### ISSUE THREAD

**Issue by brianking** [eclipse-theia/theia-blueprint#71]
macOS
Blueprint 1.12.1

Steps:
Go to File -> Settings -> Check for Updates...

Expected:
A visual cue is shown telling the user that they are up to date. This could be a popup window (recommended), or a notification.

Actual:
Nothing happens.

I'm not sure what happens when an update is available.

**Comment by jfaltermeier** [comment]
On Windows and Linux this shows "Already using the latest version" in the bottom right corner. So this might be a macOS issue (maybe related to #45 that an exception is swallowed). 

![ksnip_20210419-092546](https://user-images.githubusercontent.com/5889696/115198872-dcb03f80-a0f2-11eb-8db8-ed43abd777ee.png)

The updater logs using this framework: https://www.npmjs.com/package/electron-log
so there should be logs at: `~/Library/Logs/Theia Blueprint/main.log`

Could you please check whether an exception is logged when trying to update?
Maybe are missing some required files for the update when copying the mac package to the download area.

**Comment by brianking** [comment]
```
[2021-04-19 11:51:31.584] [info] Checking for update
[2021-04-19 11:51:31.587] [error] Error: Error: ENOENT: no such file or directory, open '/Applications/Theia.localized/Theia.app/Contents/Resources/app-update.yml'
```

So it is checking in a folder that does now exist. On my system, Theia is installed in /Applications/Theia/Theia.app. 

Somewhat related, see issue #62

**Comment by vince-fugnitto** [comment]
Would it not be better/easier to programatically get the application version, and check if a newer version is present in the `eclipse` downloads rather than rely on where it is installed?

**Comment by brianking** [comment]
The file of the latest version does not include the version number. Is there another way to get it?

https://www.eclipse.org/downloads/download.php?file=/theia/latest/macos/TheiaBlueprint.pkg&r=1

**Comment by jfaltermeier** [comment]
The dmg from https://download.eclipse.org/theia/latest/macos/ should fix this issue. 

Some mirrors for download.eclipse.org might not have caught up yet, so if there is no dmg yet, please try again later.
