### ISSUE TITLE
Update About section of this repository

### ISSUE THREAD

**Issue by brianking** [eclipse-theia/theia-blueprint#76]
Update the About section to at least add a description and web link.

<img width="356" alt="Screenshot 2021-04-15 at 15 13 50" src="https://user-images.githubusercontent.com/114116/114884058-5eefe980-9dfd-11eb-857f-2322ac723df7.png">

**Comment by vince-fugnitto** [comment]
@brianking I believe you may need to open a bugzilla for the webmaster to add content.

**Comment by brianking** [comment]
Ok will do!

**Comment by brianking** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=572884

For those not on Bugzilla, here is what I suggested. Suggestions welcome.

Suggested description: Eclipse Theia Blueprint is a template for building desktop-based products based on the Eclipse Theia platform, as well as to showcase Eclipse Theia capabilities. It is made up of a subset of existing Eclipse Theia features and extensions and can be easily downloaded and installed on all major operating system platforms.

Suggested link: https://theia-ide.org/docs/blueprint_download

**Comment by marcdumais-work** [comment]
I have access to edit that. I assumed all committers had the same. Am I the only one? When I click on the nearby gear icon, this opens:

![image](https://user-images.githubusercontent.com/25749063/114888047-eaa24f80-9dd6-11eb-87b8-3c8cd4ca4ae9.png)

Brian, if you propose some content, I can paste it in there.

**Comment by marcdumais-work** [comment]
Updated!

**Comment by brianking** [comment]
Great, thanks @marcdumais-work
