### ISSUE TITLE
Announce Installer availability

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-blueprint#8]
Messaging: Blueprint product to showcase Theia platform capabilities
- Blog Post
- Twitter: @ECDTools, @theia_ide
- Press release

Announce in stages:
- Alpha
- Beta
- Release

**Comment by koegel** [comment]
We (EclipseSource) intend to contribute to this on behalf of ST Microelectronics.

**Comment by JonasHelming** [comment]
I will create a first draft for this

**Comment by koegel** [comment]
The release is now planned for April 10th. So the announcement should be released on Monday April 12th ideally.

**Comment by koegel** [comment]
@brianking Is this feasible for you?

**Comment by brianking** [comment]
Yes, feasible. I will make sure the post is complete by the end of the week, and publish on Monday.

**Comment by koegel** [comment]
Alpha release is online and web page is updated.

**Comment by brianking** [comment]
Blog post will be up shortly today.

**Comment by brianking** [comment]
The post is now live:

https://blogs.eclipse.org/post/brian-king/eclipse-theia-blueprint-now-available-download
