### ISSUE TITLE
quality: add linting rules

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-theia/theia-blueprint#82]
#### Feature Description:

The goal would be to add linting as part of the project (`eslint`) to improve overall code quality similarly to the upstream `eclipse-theia` repository. The linting rules will help identify issues earlier in the development cycle (build and continuous-integration).

The linting rules will help:
- identify issues earlier.
- statically analyze the code to identify problems, and possibly formatting inconsistencies.
- enforce code quality and best practices.

https://github.com/eclipse-theia/theia/tree/master/configs

**Comment by koegel** [comment]
Good point, we will take a look
