### ISSUE TITLE
Include AsciiDoc extension by default

### ISSUE THREAD

**Issue by Jeeppler** [eclipse-theia/theia-blueprint#85]
Please consider adding the AsciiDoc extension to Theia Blueprint as a default extension: https://github.com/asciidoctor/asciidoctor-vscode.

**Comment by vince-fugnitto** [comment]
@Jeeppler I'm not sure it is necessary to add by default, you can install it from the extensions-view given that it is available from open-vsx:
- https://open-vsx.org/extension/asciidoctor/asciidoctor-vscode

**Comment by vince-fugnitto** [comment]
The discussion falls under the same idea as https://github.com/eclipse-theia/theia-blueprint/issues/81#issue-862898518 and https://github.com/eclipse-theia/theia-blueprint/issues/81#issuecomment-823431155. We should not bloat the application with extensions that users may or may not need, instead they are free to install them at runtime.

**Comment by Jeeppler** [comment]
@vince-fugnitto thanks for the explanation.
