### ISSUE TITLE
Show vscode extension API version in `About` dialog

### ISSUE THREAD

**Issue by Jeeppler** [eclipse-theia/theia-blueprint#86]
Currently, it is not easily possible to see what vscode extension API version Theia Blueprint supports. One would expect the supported vscode extension API in the `About` dialog next to the Theia version. 

According to `plugin-ext-vscode` Theia 1.12.0+ supports vscode 1.50.0:

```
VSCODE_DEFAULT_API_VERSION: "1.50.0" = "1.50.0"
```

Source: https://eclipse-theia.github.io/theia/docs/next/modules/plugin_ext_vscode.html

It would be nice to be able to see the vscode version in the `About` dialog.

**Comment by koegel** [comment]
Thanks, good point, we will  take a look for the beta version to fix this.

**Comment by marcdumais-work** [comment]
I think this would be generally helpful, not just for Blueprint. 

@vince-fugnitto remind me, where do we define currently the generic content for the `Help -> About`  dialog?

**Comment by vince-fugnitto** [comment]
> I think this would be generally helpful, not just for Blueprint.
> 
> @vince-fugnitto remind me, where do we define currently the generic content for the `Help -> About` dialog?

@marcdumais-work this is how the `about-dialog` is implemented (core), it currently does not know about supported API version, but a downstream extension can extend it like in the case of Blueprint. I’ve added a command to echo the API version but this is an api-sample (unpublished extension).

**Comment by marcdumais-work** [comment]
So, I think it would be nice to add it to the dialog in @theia/core, then. Or at least I would like to have this info available in various Theia apps.
