### ISSUE TITLE
Extensions are not grouped under a folder

### ISSUE THREAD

**Issue by alvsan09** [eclipse-theia/theia-blueprint#87]
### Bug Description:
The file structure is not following 'theia' or 'lerna' defaults where additional packages are consolidated
under a 'packages' folder.
So the top level project may continue to grow as extension get added which is not desirable as multiple projects may
extend a non optimal structure.

### Steps to Reproduce:

1. Open theia-blueprint repository in a file system and observe that the two existing extensions are under the top level project
i.e. 'theia-blueprint-product' and 'theia-blueprint-updater'

### Additional Information
I will submit a PR shortly after submitting this issue.

- Operating System:
- Theia Version:

**Comment by vince-fugnitto** [comment]
@alvsan09 its a known optimization that @marechal-p and I talked about previously to re-organize the repo and also add linting #82. I believe that @marechal-p already did some reorganization in preparation for #74.

**Comment by alvsan09** [comment]
> @alvsan09 its a known optimization that @marechal-p and I talked about previously to re-organize the repo and also add linting #82. I believe that @marechal-p already did some reorganization in preparation for #74.

Ok, I have closed my intended PR to take Paul's PR #88 instead.
