### ISSUE TITLE
[About dialog] fix opening of external links

### ISSUE THREAD

**Issue by ssbarnea** [eclipse-theia/theia-blueprint#95]
### Bug Description:

It seem that all hyperlinks in theia dialogs containing HTML are opened by the embedded browser and which even prevents even some of the most basic accessibility features:

* right click, copy link is missing
* inside textarea Cmd+A does not select all text
* Unable to make use of browser password managers (nativa or extensions), so logging in to github with 2FA becomes a burden

The About dialog is such a case but I am not sure if there are similar issues in other places.

**Comment by vince-fugnitto** [comment]
@ssbarnea I'm not sure I follow but it sounds like you are expecting the cloud use-case and not the electron (desktop) one?

> right click, copy link is missing

Can you identify an area where this happens in `vscode` but the `theia` does not?

> inside textarea Cmd+A does not select all text

I verified with the `scm` textarea and it works correctly.

> Unable to make use of browser password managers (nativa or extensions), so logging in to github with 2FA becomes a burden

I don't think desktop applications should make use of browser password managers.

**Comment by marcdumais-work** [comment]
@ssbarnea do you maybe refer to links contained in a HTML preview, opened in Theia's mini-browser?

**Comment by marcdumais-work** [comment]
> It seem that all hyperlinks in theia are opened by the embedded browser 

ATM blueprint only has a desktop (Electron) packaging. We are working on a browser version for easy integration in e.g. `Docker containers`. Which Theia application/version are you reporting about?

Testing with a locally built desktop Blueprint(*), URLs in editors (.md, .ts) open in the system's default browser when I control-click them. 

(*) from this PR I am working-on. I have no reason to think master would behave differently, but it could: https://github.com/eclipse-theia/theia-blueprint/pull/92

> 
> ### Additional Information
> I am sure there are accessibility features lost because of the decision to contain any browsing operation inside the app but I listed those that I was able to find in the first 5 minutes of evaluating theia.

**Comment by marcdumais-work** [comment]
![Peek 2021-05-18 12-18](https://user-images.githubusercontent.com/25749063/118687749-5cedc180-b7d3-11eb-87c1-1b24c15ec864.gif)

**Comment by ssbarnea** [comment]
Yep About dialog is the open opening another popup instead of opening system browser. In other places, like extension listing page it seems to open links as expected.

I used Theia Blueprint desk for MacOS from https://theia-ide.org/docs/blueprint_download

**Comment by vince-fugnitto** [comment]
> Yep About dialog is the open opening another popup instead of opening system browser.

@ssbarnea the `about` dialog is specific to and implemented by the application, can you clarify why you expected a desktop application's `about` dialog (like in other apps) to open in the system browser?

**Comment by marcdumais-work** [comment]
> Yep About dialog is the open opening another popup instead of opening system browser

This is annoying. Specially with links that require authentication, like some on GitHub. I think the "About" dialog should be modified to use the native default browser, for the Electron version of Blueprint.

![Peek 2021-05-18 15-15](https://user-images.githubusercontent.com/25749063/118710148-e7dab600-b7eb-11eb-80db-1554eab98b63.gif)

We recently fixed this for some dialog, but there remains some places that could be improved. Have you noted others?

**Comment by marcdumais-work** [comment]
(actually we may want to do the same with the browser version of Blueprint, so this would maybe not be Electron-specific)

**Comment by vince-fugnitto** [comment]
@marcdumais-work I made the fix in the upstream framework, it's possible that the custom blueprint `getting-started` view also needs to be updated:
- https://github.com/eclipse-theia/theia/pull/9390
- - https://github.com/eclipse-theia/theia/pull/9318

**Comment by marcdumais-work** [comment]
I am not suggesting that the `About` dialog itself be opened in an external browser, just that links it contains would be better opened in a new browser instead of the limited Electron limited pop-up browser we currently get.

**Comment by vince-fugnitto** [comment]
> I am not suggesting that the `About` dialog itself be opened in an external browser, just that links it contains would be better opened in a new browser instead of the limited Electron limited pop-up browser we currently get.

Right, but the links in the `getting-started` and `about` (which use the same code) incorrectly reference links which will not work for the electron target:

https://github.com/eclipse-theia/theia-blueprint/blob/151e0e70f4f9a984f933856c6072f8dba38d9a88/theia-extensions/theia-blueprint-product/src/browser/branding-util.tsx#L30

**Comment by marcdumais-work** [comment]
@ssbarnea It took a little while to understand - thanks for taking the time.  

Let's fix the links in the `About` dialog, so they open in the user's default browser. I have rephrased the issue title to reflect that. Please let us know if you find other places where the same is applicable.

**Comment by marcdumais-work** [comment]
> @marcdumais-work I made the fix in the upstream framework, it's possible that the custom blueprint `getting-started` view also needs to be updated:
> 
> * [eclipse-theia/theia#9390](https://github.com/eclipse-theia/theia/pull/9390)
> * [eclipse-theia/theia#9318](https://github.com/eclipse-theia/theia/pull/9318)

Thanks Vince - I think this is exactly what we need. Nice that it works both for Electron and browser.

**Comment by marcdumais-work** [comment]
@ssbarnea would you please rephrase the issue description, reflecting the findings in this discussion? If you prefer I can do it.
