### ISSUE TITLE
Implement vscode ^1.52.0 compatible API

### ISSUE THREAD

**Issue by ssbarnea** [eclipse-theia/theia-blueprint#97]
It seems that theia supports only vscode 1.50.0 which is very old and multiple key extensions and dependencies are already requiring at least 1.52.0, with a notable remarks of the `vscode-languageclient@7.0.0` which is used by a huge number of extensions.

References:
* https://github.com/redhat-developer/vscode-yaml/issues/509#issuecomment-842037147

**Comment by vince-fugnitto** [comment]
@ssbarnea thank you for opening the issue, increasing compatibility requires changes in the base framework which will then be available to the _theia blueprint_ application:
- https://github.com/eclipse-theia/theia/issues/9193

**Comment by Jeeppler** [comment]
Eclipse Theia 1.18 was released on the 30th September. With the release the API compatibility was increased from 1.50.0 to 1.53.0.
Sadly, the current AppImage of Eclipse Theia Blueprint is still based on version 1.17.2. I would really like to see a new Eclipse Theia Blueprint release based on Eclipse Theia 1.18.

**Comment by Jeeppler** [comment]
@marcdumais-work I think, this issue can be closed. Eclipse Theia Blueprint is now build against Eclipse Theia 1.19 with VSCode API version 1.53.2 compatibility.
